Client:
    type: entity
    table: client
    uniqueConstraints:
        uc_client:
            columns:
                - login
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nom:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        prenom:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        adresse:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        cp:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        ville:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        tel:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        email:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        civilite:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        login:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        password:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
